### ISSUE TITLE
make swift package manager package

### ISSUE THREAD

**Issue by potmo** [maxnatchanon/trackable-scroll-view#1]
It would be nice if you could make a SPM package so that it's easy to install this.

**Comment by jeremytandjung** [comment]
This library would be very useful in any project, you should make it a library at Cocoapods or SwiftPM!

**Comment by raziqfarid** [comment]
@maxnatchanon Please assign this to me

**Comment by maxnatchanon** [comment]
@raziqfarid  Assigned!
